#!/bin/sh

# Create canonical shared library links (e.g. libc.so -> libc.so.3)

# Copyright (C)2017-2018, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

TEMPLATE=lib*.so.*

# Look for shared library files

for F in /lib/${TEMPLATE} /usr/lib/${TEMPLATE} /usr/local/lib/${TEMPLATE} ; do
# Candidate file must not be a symbolic link
  if [ -f $F -a ! -L $F ]; then
    DIRNAME=`dirname $F`
    LONGNAME=`basename $F`
    SHORTNAME=`echo ${LONGNAME} | sed 's/\.so\..*/.so/g'`
    LINKNAME=${DIRNAME}/${SHORTNAME}
# Candidate link must not already exist
    if [ ! -L ${LINKNAME} ]; then
      ln -s $LONGNAME $DIRNAME/$SHORTNAME
    fi
  fi
done
