#!/bin/sh

# mdev helper script for setting PWM output device permissions and
# creating and removing the /dev/pwm-X:Y symlink

# Copyright (C)2017-2024, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

if [ -z "${DEVPATH}" ]; then
  exit 0
fi

SetPerms()
{
  chown root:gpio $1
  chmod $2 $1
}

# Handle PWM chip events

if [ "${ACTION}" = "add" ]; then
  SetPerms /sys${DEVPATH}          0550
  SetPerms /sys${DEVPATH}/export   0220
  SetPerms /sys${DEVPATH}/npwm     0440
  SetPerms /sys${DEVPATH}/power    0550
  SetPerms /sys${DEVPATH}/uevent   0220
  SetPerms /sys${DEVPATH}/unexport 0220
  exit 0
fi

# Handle PWM channel events

if [ "${ACTION}" = "change" -a -n "${EXPORT}" ]; then
  SetPerms /sys${DEVPATH}/${EXPORT}            0550
  SetPerms /sys${DEVPATH}/${EXPORT}/capture    0440
  SetPerms /sys${DEVPATH}/${EXPORT}/duty_cycle 0660
  SetPerms /sys${DEVPATH}/${EXPORT}/enable     0660
  SetPerms /sys${DEVPATH}/${EXPORT}/period     0660
  SetPerms /sys${DEVPATH}/${EXPORT}/polarity   0660
  SetPerms /sys${DEVPATH}/${EXPORT}/power      0550
  SetPerms /sys${DEVPATH}/${EXPORT}/uevent     0220
  exit 0
fi
