#!/bin/sh

# mdev helper to set GPIO device permissions and create and remove
# the /dev/gpioX symlink

# Copyright (C)2016-2018, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

if [ -z "${DEVPATH}" ]; then
  exit 0
fi

SetPerms()
{
  chown root:gpio $1
  chmod $2 $1
}

DEVNAME=`basename ${DEVPATH}`

# Handle GPIO pin events

echo ${DEVNAME} | egrep 'gpio[0-9]+'

if [ $? -eq 0 ]; then
  if [ "$ACTION" = "add" ]; then
    SetPerms /sys${DEVPATH}            0750
    SetPerms /sys${DEVPATH}/active_low 0660
    SetPerms /sys${DEVPATH}/direction  0660
    SetPerms /sys${DEVPATH}/edge       0660
    SetPerms /sys${DEVPATH}/value      0660

    ln -s -f /sys${DEVPATH}/value /dev/${DEVNAME}
  fi

  if [ "$ACTION" = "remove" ]; then
    rm -f /dev/${DEVNAME}
  fi
fi
