#!/bin/sh

# mdev helper to perform optional processing for raw HID devices

# Copyright (C)2017-2024, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

if [ "${SUBSYSTEM}" = "hidraw" -a "${ACTION}" = "add" ]; then

# Look for idVendor and idProduct files

  DEVPATH=/sys${DEVPATH}
  VIDPATH=${DEVPATH}/../../../../idVendor
  PIDPATH=${DEVPATH}/../../../../idProduct
  SERIALPATH=${DEVPATH}/../../../../serial

  if [ -f ${VIDPATH} -a -f ${PIDPATH} ]; then

# Extract vendor and product identifiers from idVendor and idProduct

    VID=`cat ${VIDPATH} | tr '[A-Z]' '[a-z]'`
    PID=`cat ${PIDPATH} | tr '[A-Z]' '[a-z]'`
    SCRIPTNAME=setup-${VID}:${PID}

# Look for a matching device setup program in /usr/libexec and /usr/local/libexec

    if [ -x /usr/libexec/${SCRIPTNAME} ]; then
      /usr/libexec/${SCRIPTNAME}
    fi

    if [ -x /usr/local/libexec/${SCRIPTNAME} ]; then
      /usr/local/libexec/${SCRIPTNAME}
    fi

# Create special symlinks for designated USB raw HID devices

    grep -q -i "${VID}:${PID}" /etc/hidraw.conf

    if [ $? -eq 0 ]; then
      ln -s -f ${MDEV} /dev/hidraw-${VID}:${PID}

      if [ -f ${SERIALPATH} ]; then
        ln -s -f ${MDEV} /dev/hidraw-${VID}:${PID}-`cat ${SERIALPATH}`
      fi
    fi
  fi
fi

if [ "${SUBSYSTEM}" = "hidraw" -a "${ACTION}" = "remove" ]; then

# Remove symbolic link(s) when a hidraw device is removed

  for L in `find /dev/ -type l` ; do
    if [ "`readlink ${L}`" = "${MDEV}" ]; then
      rm ${L}
    fi
  done
fi
