#!/bin/sh

# Post-installation script for the E-MailRelay package for MuntsOS

# Copyright (C)2020, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

mkdir -p /usr/local/etc/emailrelay

# Create initial auth.conf, if necessary

if [ ! -f /usr/local/etc/emailrelay/auth.conf ]; then
  cat <<EOD >/usr/local/etc/emailrelay/auth.conf
# Replace username and password with your credentials
client plain username password
EOD
  chmod 400 /usr/local/etc/emailrelay/auth.conf
fi

# Create initial emailrelay.conf, if necessary

if [ ! -f /usr/local/etc/emailrelay/emailrelay.conf ]; then
  cat <<EOD >/usr/local/etc/emailrelay/emailrelay.conf
AUTHFILE=/usr/local/etc/emailrelay/auth.conf
SPOOLDIR=/var/spool/emailrelay
# Replace servername and port with your SMTP smarthost server
SMARTHOST=servername:port
EOD
  chmod 444 /usr/local/etc/emailrelay/emailrelay.conf
fi
