package com.munts.muntsos.examples.GPIO.ONCRPC;

/*
 * Automatically generated by jrpcgen 1.0.7 on 6/5/17 9:04 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

/**
 * The class <code>gpio_server_oncrpcClient</code> implements the client stub proxy
 * for the GPIO_SERVER_ONCRPC remote program. It provides method stubs
 * which, when called, in turn call the appropriate remote method (procedure).
 */
public class gpio_server_oncrpcClient extends OncRpcClientStub {

    /**
     * Constructs a <code>gpio_server_oncrpcClient</code> client stub proxy object
     * from which the GPIO_SERVER_ONCRPC remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public gpio_server_oncrpcClient(InetAddress host, int protocol)
           throws OncRpcException, IOException {
        super(host, gpio_server_oncrpc.GPIO_SERVER_ONCRPC, 1, 0, protocol);
    }

    /**
     * Constructs a <code>gpio_server_oncrpcClient</code> client stub proxy object
     * from which the GPIO_SERVER_ONCRPC remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public gpio_server_oncrpcClient(InetAddress host, int port, int protocol)
           throws OncRpcException, IOException {
        super(host, gpio_server_oncrpc.GPIO_SERVER_ONCRPC, 1, port, protocol);
    }

    /**
     * Constructs a <code>gpio_server_oncrpcClient</code> client stub proxy object
     * from which the GPIO_SERVER_ONCRPC remote program can be accessed.
     * @param client ONC/RPC client connection object implementing a particular
     *   protocol.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public gpio_server_oncrpcClient(OncRpcClient client)
           throws OncRpcException, IOException {
        super(client);
    }

    /**
     * Constructs a <code>gpio_server_oncrpcClient</code> client stub proxy object
     * from which the GPIO_SERVER_ONCRPC remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public gpio_server_oncrpcClient(InetAddress host, int program, int version, int protocol)
           throws OncRpcException, IOException {
        super(host, program, version, 0, protocol);
    }

    /**
     * Constructs a <code>gpio_server_oncrpcClient</code> client stub proxy object
     * from which the GPIO_SERVER_ONCRPC remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public gpio_server_oncrpcClient(InetAddress host, int program, int version, int port, int protocol)
           throws OncRpcException, IOException {
        super(host, program, version, port, protocol);
    }

    /**
     * Call remote procedure gpio_open_1.
     * @param pin parameter (of type int) to the remote procedure call.
     * @param direction parameter (of type int) to the remote procedure call.
     * @param state parameter (of type int) to the remote procedure call.
     * @return Result from remote procedure call (of type int).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public int gpio_open_1(int pin, int direction, int state)
           throws OncRpcException, IOException {
        class XdrAble$ implements XdrAble {
            public int pin;
            public int direction;
            public int state;
            public void xdrEncode(XdrEncodingStream xdr)
                throws OncRpcException, IOException {
                xdr.xdrEncodeInt(pin);
                xdr.xdrEncodeInt(direction);
                xdr.xdrEncodeInt(state);
            }
            public void xdrDecode(XdrDecodingStream xdr)
                throws OncRpcException, IOException {
            }
        };
        XdrAble$ args$ = new XdrAble$();
        args$.pin = pin;
        args$.direction = direction;
        args$.state = state;
        XdrInt result$ = new XdrInt();
        client.call(gpio_server_oncrpc.gpio_open_1, gpio_server_oncrpc.GPIO_SERVER_ONCRPC_VERS, args$, result$);
        return result$.intValue();
    }

    /**
     * Call remote procedure gpio_close_1.
     * @param pin parameter (of type int) to the remote procedure call.
     * @return Result from remote procedure call (of type int).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public int gpio_close_1(int pin)
           throws OncRpcException, IOException {
        XdrInt args$ = new XdrInt(pin);
        XdrInt result$ = new XdrInt();
        client.call(gpio_server_oncrpc.gpio_close_1, gpio_server_oncrpc.GPIO_SERVER_ONCRPC_VERS, args$, result$);
        return result$.intValue();
    }

    /**
     * Call remote procedure gpio_read_1.
     * @param pin parameter (of type int) to the remote procedure call.
     * @return Result from remote procedure call (of type int).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public int gpio_read_1(int pin)
           throws OncRpcException, IOException {
        XdrInt args$ = new XdrInt(pin);
        XdrInt result$ = new XdrInt();
        client.call(gpio_server_oncrpc.gpio_read_1, gpio_server_oncrpc.GPIO_SERVER_ONCRPC_VERS, args$, result$);
        return result$.intValue();
    }

    /**
     * Call remote procedure gpio_write_1.
     * @param pin parameter (of type int) to the remote procedure call.
     * @param state parameter (of type int) to the remote procedure call.
     * @return Result from remote procedure call (of type int).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public int gpio_write_1(int pin, int state)
           throws OncRpcException, IOException {
        class XdrAble$ implements XdrAble {
            public int pin;
            public int state;
            public void xdrEncode(XdrEncodingStream xdr)
                throws OncRpcException, IOException {
                xdr.xdrEncodeInt(pin);
                xdr.xdrEncodeInt(state);
            }
            public void xdrDecode(XdrDecodingStream xdr)
                throws OncRpcException, IOException {
            }
        };
        XdrAble$ args$ = new XdrAble$();
        args$.pin = pin;
        args$.state = state;
        XdrInt result$ = new XdrInt();
        client.call(gpio_server_oncrpc.gpio_write_1, gpio_server_oncrpc.GPIO_SERVER_ONCRPC_VERS, args$, result$);
        return result$.intValue();
    }

}
// End of gpio_server_oncrpcClient.java
