package com.munts.muntsos.examples.GPIO.ONCRPC;

/*
 * Automatically generated by jrpcgen 1.0.7 on 6/5/17 9:04 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "gpio_server_oncrpc" ONC/RPC program.
 */
public interface gpio_server_oncrpc {
    public static final int gpio_read_1 = 3;
    public static final int GPIO_SERVER_ONCRPC_VERS = 1;
    public static final int gpio_close_1 = 2;
    public static final int gpio_open_1 = 1;
    public static final int GPIO_SERVER_ONCRPC = 30000;
    public static final int gpio_write_1 = 4;
}
// End of gpio_server_oncrpc.java
