/*
 * Automatically generated by jrpcgen 1.0.7 on 4/29/2014
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "missile" ONC/RPC program.
 */
public class missile {
    public static readonly int CMD_UP = 0x02;
    public static readonly int CMD_STOP = 0x20;
    public static readonly int CMD_CW = 0x08;
    public static readonly int CMD_FIRE = 0x10;
    public static readonly int MISSILE_VERS = 1;
    public static readonly int missile_command_1 = 1;
    public static readonly int CMD_DOWN = 0x01;
    public static readonly int CMD_NOP = 0x00;
    public static readonly int MISSILE = 20000;
    public static readonly int CMD_CCW = 0x04;
}
// End of missile.cs
