#!/bin/sh

# Post-Install script for LPC1114 I/O Processor

# Copyright (C)2016-2025, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Link startup script

ln -s /usr/local/libexec/expansion_lpc1114_startup /etc/rc.d/S50-expansion_lpc1114

# Add entries to /etc/services, if necessary

grep -q 'spiagent-xmlrpc' /etc/services
if [ $? -ne 0 ]; then
  sed -i '/8080\//d' /etc/services
  echo "" >>/etc/services
  echo "# LPC1114 I/O Processor XML-RPC service" >> /etc/services
  echo "spiagent-xmlrpc 8080/tcp" >>/etc/services
fi

grep -q 'spiagent-http' /etc/services
if [ $? -ne 0 ]; then
  sed -i '/8081\//d' /etc/services
  echo "" >>/etc/services
  echo "# LPC1114 I/O Processor HTTP service" >> /etc/services
  echo "spiagent-http 8081/tcp" >>/etc/services
fi

grep -q 'spiagent-zeromq' /etc/services
if [ $? -ne 0 ]; then
  sed -i '/8082\//d' /etc/services
  echo "" >>/etc/services
  echo "# LPC1114 I/O Processor ZeroMQ service" >> /etc/services
  echo "spiagent-zeromq 8082/tcp" >>/etc/services
fi

grep -q 'spiagent-linx' /etc/services
if [ $? -ne 0 ]; then
  sed -i '/8086\//d' /etc/services
  echo "" >>/etc/services
  echo "# LPC1114 I/O Processor LabView LINX service" >> /etc/services
  echo "spiagent-linx 8086/tcp" >>/etc/services
fi

grep -q 'spiagent-remoteio-udp' /etc/services
if [ $? -ne 0 ]; then
  sed -i '/8087\//d' /etc/services
  echo "" >>/etc/services
  echo "# LPC1114 I/O Processor Remote I/O service" >> /etc/services
  echo "spiagent-remoteio-udp 8087/udp" >>/etc/services
fi
grep -q 'spiagent-remoteio-zeromq' /etc/services
if [ $? -ne 0 ]; then
  sed -i '/8088\//d' /etc/services
  echo "" >>/etc/services
  echo "# LPC1114 I/O Processor Remote I/O service" >> /etc/services
  echo "spiagent-remoteio-zeromq 8088/tcp" >>/etc/services
fi

# Install initial configuration file

ETC=/usr/local/etc
SHARE=/usr/local/share/lpc1114
CFG=expansion_lpc1114.config

if [ ! -f ${ETC}/${CFG} ]; then
  test -f ${SHARE}/${CFG}.${BOARDBASE}        && cp ${SHARE}/${CFG}.${BOARDBASE}    ${ETC}/${CFG}
  echo ${BOARDNAME} | grep -q BeagleBoneGreen && cp ${SHARE}/${CFG}.BeagleBoneGreen ${ETC}/${CFG}
  echo ${BOARDNAME} | grep -q RaspberryPi     && cp ${SHARE}/${CFG}.RaspberryPi     ${ETC}/${CFG}
fi

# Restore saved configuration file

if [ -f /usr/local/etc/expansion_lpc1114.config.save ]; then
  mv /usr/local/etc/expansion_lpc1114.config.save /usr/local/etc/expansion_lpc1114.config
fi
