#!/bin/sh

# Post-Install script for MuntsOS GPIO server package

# Copyright (C)2016-2024, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Add entries to /etc/rpc, if necessary

grep -q gpio /etc/rpc
if [ $? -eq 1 ]; then
  echo ""				>>/etc/rpc
  echo "# GPIO over ONC RPC"		>>/etc/rpc
  echo -e "gpio\t30000"			>>/etc/rpc
fi

# Add entries to /etc/services, if necessary

grep -q 'gpio-http' /etc/services
if [ $? -ne 0 ]; then
  echo ""				>>/etc/services
  echo "# GPIO over HTTP"		>>/etc/services
  echo "gpio-http 8083/tcp"		>>/etc/services
fi

grep -q 'gpio-xmlrpc' /etc/services
if [ $? -ne 0 ]; then
  echo ""				>>/etc/services
  echo "# GPIO over XML-RPC"		>>/etc/services
  echo "gpio-xmlrpc 8084/tcp"		>>/etc/services
fi

grep -q 'gpio-linx' /etc/services
if [ $? -ne 0 ]; then
  echo ""				>>/etc/services
  echo "# GPIO over LabView LINX"	>>/etc/services
  echo "gpio-linx 8085/tcp"		>>/etc/services
fi

grep -q 'remoteio-udp' /etc/services
if [ $? -ne 0 ]; then
  echo ""				>>/etc/services
  echo "# GPIO over UDP"		>>/etc/services
  echo "remoteio-udp 8087/udp"		>>/etc/services
fi

# Scan libraries

linklibs
ldconfig
