#!/bin/sh

# Startup script for a dedicated GPIO server using the Hylands userspace
# GPIO library

# Copyright (C)2013-2024, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Start rpcbind, if necessary

iptables -w -v -L | grep -q dpt:sunrpc
if [ $? -ne 0 ]; then
  iptables -w -A INPUT -p tcp -m conntrack --ctstate NEW --dport 111 -j ACCEPT
  iptables -w -A INPUT -p udp -m conntrack --ctstate NEW --dport 111 -j ACCEPT
  rpcbind
fi

# Run ldconfig to pick up any new libraries

ldconfig

# Start servers

/usr/local/libexec/gpio_server_http
/usr/local/libexec/gpio_server_linx
/usr/local/libexec/gpio_server_oncrpc
/usr/local/libexec/gpio_server_xmlrpc
/usr/local/libexec/remoteio_server
sleep 5

# Add firewall rules

iptables -w -A INPUT -p tcp -m conntrack --ctstate NEW --dport gpio-http    -j ACCEPT
iptables -w -A INPUT -p tcp -m conntrack --ctstate NEW --dport gpio-linx    -j ACCEPT
iptables -w -A INPUT -p tcp -m conntrack --ctstate NEW --dport gpio-xmlrpc  -j ACCEPT
iptables -w -A INPUT -p udp -m conntrack --ctstate NEW --dport remoteio-udp -j ACCEPT

rpcinfo -p localhost | awk '/30000/ { printf("iptables -w -A INPUT -p %s -m conntrack --ctstate NEW --dport %s -j ACCEPT\n", $3, $4); }' | sh
