#!/bin/sh

# Post-installation script for DragonFly Mail Agent package for MuntsOS

# Copyright (C)2020-2024, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Create mail user and group, if necessary

grep -q -E '^mail::' /etc/group

if [ $? -ne 0 ]; then
  addgroup mail
fi

grep -q -E '^mail:x:' /etc/passwd

if [ $? -ne 0 ]; then
  adduser -h /var/empty -g "Mail Transfer Agent" -G mail -s /bin/false -D -H mail
fi

# Create configuration and spool directories

mkdir -p /usr/local/etc/dma
mkdir -p /var/spool/dma

# Create initial auth.conf, if necessary

if [ ! -f /usr/local/etc/dma/auth.conf ]; then
  cat <<EOD >/usr/local/etc/dma/auth.conf
username|smarthost:password
EOD
fi

# Create initial dma.conf, if necessary

if [ ! -f /usr/local/etc/dma/dma.conf ]; then
  cat <<EOD >/usr/local/etc/dma/dma.conf
SMARTHOST smarthost
PORT 587
AUTHPATH /usr/local/etc/dma/auth.conf
SECURETRANSFER
STARTTLS
MASQUERADE username@domain
EOD
fi

# Fixup permissions and ownerships

chmod 500 /usr/local/etc/dma
chmod 400 /usr/local/etc/dma/auth.conf
chmod 400 /usr/local/etc/dma/dma.conf
chmod 700 /var/spool/dma

chown -R mail.mail /usr/local/etc/dma
chown -R mail.mail /var/spool/dma

# Replace /usr/sbin/sendmail

ln -s -f /usr/local/libexec/dma /usr/sbin/sendmail
