#!/bin/sh

# Post-Install script for Python 3 Runtime extension package

# Copyright (C)2024, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Scan libraries

linklibs
ldconfig

# Create convenience symlinks for existing python script programs

ln -s -f /usr/local/bin/python3 /bin/python
ln -s -f /usr/local/bin/python3 /bin/python3
ln -s -f /usr/local/bin/python3 /usr/bin/python
ln -s -f /usr/local/bin/python3 /usr/bin/python3

# Suppress the warning about superuser running pip

grep -q "PIP_ROOT_USER_ACTION=ignore" /etc/environment
test $? -eq 0 || echo "PIP_ROOT_USER_ACTION=ignore" >> /etc/environment

# Save site-packages

echo "/usr/local/lib/python@@MAJORVER@@/site-packages" >>/etc/changes.manifest

test -f /tmp/booting.flag && umount /boot

sysconfig --save

test -f /tmp/booting.flag && mount /boot

exit 0
