/*
 * Automatically generated by jrpcgen 1.0.7 on 06/10/2016
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "gpio_server_oncrpc" ONC/RPC program.
 */
public class gpio_server_oncrpc {
    public static readonly int GPIO_SERVER_ONCRPC = 30000;
    public static readonly int GPIO_SERVER_ONCRPC_VERS = 1;
    public static readonly int gpio_write_1 = 4;
    public static readonly int gpio_open_1 = 1;
    public static readonly int gpio_read_1 = 3;
    public static readonly int gpio_close_1 = 2;
}
// End of gpio_server_oncrpc.cs
