/*
 * Automatically generated by jrpcgen 1.0.7 on 06/10/2016
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public class GPIO_DIRECTION {

    public static readonly int GPIO_DIRECTION_INPUT = 0;
    public static readonly int GPIO_DIRECTION_OUTPUT = 1;

}
// End of GPIO_DIRECTION.cs
