#! /bin/sh

# Release MuntsOS Embedded Linux cross-toolchain tarballs

# Copyright (C)2023, Philip Munts.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Transform named parameters to environment variables

for x ; do export ${x%=*}="${x#*=}"; done

BUILDNUM=${BUILDNUM:-1}
VERSION=`date +%Y.%j.${BUILDNUM}`
SERVERDIR=${SERVERDIR:-${HOME}}

tarone()
{
  echo ${1}
  tar czf muntsos-dev-${1}-${VERSION}.tgz -C /usr/local fpc-${2} gcc-${2} share/libsimpleio share/muntsos
}

tarone beaglebone   arm-linux-gnueabihf-muntsos-beaglebone
tarone raspberrypi1 arm-linux-gnueabihf-muntsos-raspberrypi1
tarone raspberrypi2 arm-linux-gnueabihf-muntsos-raspberrypi2
tarone aarch64      aarch64-linux-gnu-muntsos

scp *.tgz ${SERVERDIR}
