#!/bin/sh

# Format media (e.g. SD card) for MuntsOS Embedded Linux

# Copyright (C)2018-2022, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

ShowUsage()
{
  echo ""
  echo "Format media for MuntsOS Embedded Linux"
  echo ""
  echo "Usage: format <drive> <label>"
  echo ""
  echo "where <drive> is sdg etc."
  echo ""
  exit 1
}

# Verify parameters

if [ $# -lt 1 -o $# -gt 2 ]; then
  ShowUsage
fi

if [ ! -b $1 ]; then
  ShowUsage
fi

# Unmount any automounted partitions

for P in ${1}?*; do
  if [ -b "$P" ]; then
    umount $P
  fi
done

# Nuke the drive

dd if=/dev/zero of=${1} bs=512 count=10000 >/dev/null 2>&1
partprobe
sleep 1

# Partition the drive

echo ",+,0x0C,*" | sfdisk -q -w always $1
partprobe
sleep 1

# Format the FAT32 filesystem

if [ -n "$2" ]; then
  mkfs.vfat -F 32 -n "`echo $2 | tr '[a-z]' '[A-Z]'`" ${1}1
else
  mkfs.vfat -F 32 ${1}1
fi
