#! /bin/sh

# Mirror curated MuntsOS Embedded Linux extensions to current directory

# Copyright (C)2025, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

SRCURL=https://repo.munts.com/muntsos/extensions
ARCHS="aarch64"
TOOLCHAINREVISION=10

# Download curated extensions

for A in ${ARCHS} ; do
  # Download manifest for this architecture
  MANIFEST=.extensions.manifest${TOOLCHAINREVISION}.${A}
  wget -nv ${SRCURL}/${MANIFEST} -O ${MANIFEST}
  # Create list of extension files for this architecture
  EXTENSIONS=`awk < ${MANIFEST} '{ print $2 }'`
  # Download extension files for this architecture
  for E in ${EXTENSIONS} ; do
    wget -nc -nv ${SRCURL}/${E} -O ${E}
  done
done

# Append local extensions to the manifest

#sha512sum mailtunnel*all.deb | sort -k2 >> .extensions.manifest${TOOLCHAINREVISION}.aarch64
