#!/bin/sh

# This script sets up a Fedora Linux machine for developing applications for
# MuntsOS Embedded Linux

# Copyright (C)2023, Philip Munts.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

MACHINE=`uname -m`

echo ""
echo "Check for Fedora system package updates..."
echo ""

sudo dnf check-update
sudo dnf -y upgrade

echo ""
echo "Install some Fedora system packages..."
echo ""

sudo dnf -y -q group install "C Development Tools and Libraries"
sudo dnf -y -q group install "Development Tools"
sudo dnf -y -q install gcc-gnat
sudo dnf -y -q install git
sudo dnf -y -q install gprbuild
sudo dnf -y -q install wget

sudo ln -s -f ../libexec/gprbuild /usr/lib/gprbuild

echo ""
echo "Install MuntsOS Embedded Linux cross-toolchain packages..."
echo ""

wget -q -r -np http://repo.munts.com/muntsos/rpms/
sudo rpm -U --force repo.munts.com/muntsos/rpms/*.rpm
rm -rf repo.munts.com

echo ""
echo "Install Alire..."
echo ""

wget -q https://github.com/alire-project/alire/releases/download/v1.2.2/alr-1.2.2-bin-x86_64-linux.zip
sudo unzip -o -q alr*.zip bin/alr -d /usr/local
sudo chmod 555 /usr/local/bin/alr
rm alr*.zip
