#!/bin/sh

# This script sets up a Debian Linux machine for developing applications for
# MuntsOS Embedded Linux

# Copyright (C)2019-2023, Philip Munts.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

MACHINE=`uname -m`

# Install necessary system packages

sudo apt update
sudo apt -y upgrade
sudo apt -y install build-essential git gprbuild wget

if [ -d /usr/libexec/gprbuild ]; then
  sudo ln -s -f ../libexec/gprbuild /usr/lib/gprbuild
fi

# Register Munts Technologies Debian package repository

if [ ! -f /etc/apt/sources.list.d/repo.munts.com.list ]; then
  if [ "${MACHINE}" = "x86_64" ]; then
    # 64-Bit Debian amd64
    wget http://repo.munts.com/debian11/PublicKey.txt && sudo apt-key add PublicKey.txt && rm PublicKey.txt
    wget http://repo.munts.com/debian11/amd64/munts-repo.deb && sudo dpkg -i munts-repo.deb && rm munts-repo.deb
  fi

  if [ "${MACHINE}" = "aarch64" ]; then
    # 64-Bit Debian arm64
    wget http://repo.munts.com/debian11/PublicKey.txt && sudo apt-key add PublicKey.txt && rm PublicKey.txt
    wget http://repo.munts.com/debian11/arm64/munts-repo.deb && sudo dpkg -i munts-repo.deb && rm munts-repo.deb
  fi
fi

# Install packages from the Munts Technologies Debian package repository

sudo apt update
sudo apt -y install muntsos-dev alire

alr toolchain --disable-assistant
