#!/bin/sh

# This script sets up a RHEL Linux machine for developing applications for
# MuntsOS Embedded Linux

# Copyright (C)2023-2024, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

MACHINE=`uname -m`

echo ""
echo "Upgrade any outdated system packages..."
echo ""

sudo dnf check-update
sudo dnf -y upgrade

echo ""
echo "Install some system packages..."
echo ""

sudo dnf -y -q group install "Development Tools"
sudo dnf -y -q install wget

echo ""
echo "Install MuntsOS Embedded Linux cross-toolchain packages..."
echo ""

wget -q -r -np http://repo.munts.com/muntsos/rpms/
sudo rpm -U repo.munts.com/muntsos/rpms/*.rpm
rm -rf repo.munts.com

which gprbuild >/dev/null 2>&1

if [ $? -eq 1 ]; then
  echo ""
  echo "Install Alire gprbuild..."
  echo ""

  sudo /usr/local/bin/alr toolchain --install-dir /usr/local --install gprbuild
  sudo ln -s -f /usr/local/gprbuild*/libexec/gprbuild /usr/lib/gprbuild
  cd /usr/local/bin && for P in ../gprbuild*/bin/* ; do sudo ln -s -f $P ; done
fi

alr toolchain --disable-assistant
