# Global definitions for cross-toolchains built with Crosstool-NG

# Copyright (C)2017-2021, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

CONFIGURE_NAME	= $(GCCARCH)-linux-$(GCCABI)
TOOLCHAIN_NAME	= $(CONFIGURE_NAME)-muntsos-$(BOARDBASE)-$(TOOLCHAIN_BUILDER)
TOOLCHAIN_DIR	= /usr/local/gcc-$(TOOLCHAIN_NAME)
CROSS_COMPILE	= $(TOOLCHAIN_DIR)/bin/$(CONFIGURE_NAME)-
GCCINCDIR	= $(TOOLCHAIN_DIR)/$(CONFIGURE_NAME)/include
GCCLIBDIR	= $(TOOLCHAIN_DIR)/$(CONFIGURE_NAME)/lib
GCCSYSROOT	= $(TOOLCHAIN_DIR)/$(CONFIGURE_NAME)/libc
GCCLDLINUX	= $(GCCSYSROOT)/lib/$(LOADER)

# C/C++

CFLAGS		+= -DMUNTSOS

# Free Pascal

FPC_COMMAND	= ppcross$(ARCH)
FPC_FLAGS	+= -dMUNTSOS
FPC		= /usr/local/fpc-$(TOOLCHAIN_NAME)/bin/$(FPC_COMMAND)

# GNAT Ada

GNATPREFIX	= $(CROSS_COMPILE)
GPRBUILDCONFIG	= --config=$(TOOLCHAIN_DIR)/share/gpr/$(BOARDBASE).cgpr
